DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS games;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE games (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  console TEXT NOT NULL
);

CREATE TABLE playedgames {
  game_id INTEGER PRIMARY KEY,
  
  FOREIGN KEY (game_id) REFERENCES games (id)
};