DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS games;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE games (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  player_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  console TEXT NOT NULL,
  FOREIGN KEY (player_id) REFERENCES user (id)
);